modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Saereth/BloodmagicTeams/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
credits = "${mod_credits}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${loader_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "bloodmagic"
    mandatory = true
    versionRange = "[3.3.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "ftbteams"
    mandatory = true
    versionRange = "[2001.1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "ftblibrary"
    mandatory = true
    versionRange = "[2001.1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "patchouli"
    mandatory = false
    versionRange = "[1.20.1-84,)"
    ordering = "AFTER"
    side = "BOTH"
