modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

# NeoForge dependency
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

# Minecraft dependency
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# Blood Magic dependency
[[dependencies.${mod_id}]]
modId="bloodmagicnv"
type="required"
versionRange="*"
ordering="AFTER"
side="BOTH"

# FTB Teams dependency
[[dependencies.${mod_id}]]
modId="ftbteams"
type="required"
versionRange="*"
ordering="AFTER"
side="BOTH"

# FTB Library dependency (required by FTB Teams)
[[dependencies.${mod_id}]]
modId="ftblibrary"
type="required"
versionRange="*"
ordering="AFTER"
side="BOTH"
